"""Are the R07 copies in the Studio workspaces still what the converter produces?

    py tmp/r07_workspace_drift.py

The converter gained three extensions for R10 (textAdjust, kind="break", and moving a band's
printWhenExpression from an attribute to a 6.x child element). The R07 sweep re-ran 21/21
IDENTICAL afterwards, so the PIPELINE is sound - but the files already sitting in the workspace
were generated by the OLD converter and were never regenerated.

If the new converter emits different bytes for any R07 report, the workspace copy is stale.
That matters most for the band change: a stale copy would still carry printWhenExpression as an
attribute, which the 6.x XSD rejects outright - the exact failure that stopped R10.030.

Compares, per report:
  6.17.0 workspace  <ws>/R07.XXX/<stem>_6_17.jrxml   vs  <report>/output/jr6/<stem>_jr6.jrxml
  7.0.3  workspace  <ws>/R07.XXX/<stem>.jrxml        vs  <report>/output/<stem>.jrxml

Read-only.
"""
import os

S = r"C:\Projects\INPEX\sources\CrystalReports"
W6 = (r"C:\Tools\jasper\TIB_js-studiocomm_6.17.0_windows_x86_64\jaspersoftstudio"
      r"\JaspersoftWorkspace\INPEX_JasperReports\R07.XXX")
W7 = (r"C:\Tools\jasper\js-studiocomm_7.0.3_windows_x86_64\jaspersoftstudio"
      r"\JaspersoftWorkspace\INPEX_JasperReports\R07.XXX")

reps = sorted(d for d in os.listdir(S) if d.startswith("R07.0"))


def body(p):
    """File content minus the generated header comment, which carries a timestamp."""
    t = open(p, encoding="utf-8", errors="replace").read().replace("\r\n", "\n")
    if t.startswith("<?xml") and "-->" in t[:2000]:
        t = t[t.index("-->") + 3:]
    return t.strip()


print("%-9s %-46s %-12s %s" % ("report", "stem", "6.17 copy", "7.0.3 copy"))
print("-" * 92)
drift6 = drift7 = miss6 = miss7 = same = 0
for rep in reps:
    out = os.path.join(S, rep, "output")
    if not os.path.isdir(out):
        continue
    for fn in sorted(f for f in os.listdir(out)
                     if f.endswith(".jrxml") and "backup" not in f
                     and "variant" not in f.lower()):
        stem = fn[:-6]
        # --- 6.17
        fresh6 = os.path.join(out, "jr6", stem + "_jr6.jrxml")
        ws6 = os.path.join(W6, stem + "_6_17.jrxml")
        if not os.path.exists(fresh6):
            s6 = "no jr6 built"
        elif not os.path.exists(ws6):
            s6 = "NOT IN WS"
            miss6 += 1
        elif body(fresh6) == body(ws6):
            s6 = "same"
        else:
            s6 = "*** DRIFT"
            drift6 += 1
        # --- 7.0.3
        ws7 = os.path.join(W7, fn)
        if not os.path.exists(ws7):
            s7 = "NOT IN WS"
            miss7 += 1
        elif body(os.path.join(out, fn)) == body(ws7):
            s7 = "same"
        else:
            s7 = "*** DRIFT"
            drift7 += 1
        if s6 == "same" and s7 == "same":
            same += 1
        print("%-9s %-46s %-12s %s" % (rep, stem[:46], s6, s7))

print("\n6.17 workspace: %d drifted, %d missing" % (drift6, miss6))
print("7.03 workspace: %d drifted, %d missing" % (drift7, miss7))
print("%d report(s) match in both" % same)
print("\n%s" % ("OK - workspaces match the current converter output"
                if not (drift6 or drift7 or miss6 or miss7)
                else "ACTION NEEDED - refresh the drifted/missing copies"))
