-- =====================================================================================================
-- ECIS Excel-upload interface config: CLAUDE_WELL_TEST   (sandbox demo)
-- Style mirrors Pluto 050_Interfaces (V1.0.0.0050.0100__PROD_TARGET_IMPORT_MAPPING.sql): writes through the
-- OV_* object views (they handle object_id/rec_id/date-effective), FK by business CODE (no hardcoded GUIDs),
-- one begin..end; block, no EXCEPTION handling, no COMMIT inside the file.
-- UPDATE-INSERT (re-runnable): each object UPDATEs if present, else INSERTs. REV_TEXT='ECPR-XXXX' on every DML
-- (REPLACE 'ECPR-XXXX' with the real change ticket).
-- Dependency order: INTERFACE -> SOURCE_MAPPING -> SOURCE_PATH (parent resolved by subquery) -> TARGET_MAPPING.
-- Maps Excel sheet 'Data' (Well | Date | Pressure) -> PWEL_DAY_STATUS.AVG_BH_PRESS keyed by well + date.
--
-- STYLE per user (2026-06-21): OV_* object views, FK by business CODE, single begin..end; block, NO MERGE,
-- NO EXCEPTION handling, NO COMMIT in the file, update-insert, REV_TEXT on every DML.
-- STATUS: interface + source mappings + target sections verified to execute via the OV_* views. The
-- source-mapping-command (OV_IMP_SOURCE_PATH) inserts still need a runtime fix: on a clean slate the path
-- INSERT raises ORA-00001 on UK_IMP_SOURCE_PATH_1 (IMP_SOURCE_MAPPING_ID, TYPE, SORT_ORDER) via the
-- IUD_IMP_SOURCE_PATH instead-of trigger - likely the mapping-create seeds a default path that this insert
-- then duplicates; the path UPDATE/INSERT-not-exists guards need to account for that. *** PATHS SECTION
-- RUNTIME-VERIFY PENDING. *** (The working live config is the equivalent built via the UI builder scripts.)
-- =====================================================================================================
begin

  -- 1) INTERFACE -----------------------------------------------------------------------------------
  UPDATE OV_IMP_SOURCE_INTERFACE
     SET NAME='Claude Well Test', FUNCTIONAL_AREA_CODE='ECIS', INTERFACE_TYPE='INSERT_UPDATE',
         TRANSACTION_TYPE='ROW', SOURCE_TYPE='EXCEL', STAGING_VALIDATION_IND='N', EC_VALID_LEVEL='P',
         EC_DATA_LEVEL='P', OVERWRITE='FULL', REV_TEXT='ECPR-XXXX'
   WHERE CODE='CLAUDE_WELL_TEST';
  INSERT INTO OV_IMP_SOURCE_INTERFACE (CODE, OBJECT_START_DATE, NAME, FUNCTIONAL_AREA_CODE, INTERFACE_TYPE,
         TRANSACTION_TYPE, SOURCE_TYPE, STAGING_VALIDATION_IND, EC_VALID_LEVEL, EC_DATA_LEVEL, OVERWRITE, REV_TEXT)
  SELECT 'CLAUDE_WELL_TEST', to_date('1900-01-01T00:00:00','yyyy-mm-dd"T"hh24:mi:ss'), 'Claude Well Test',
         'ECIS', 'INSERT_UPDATE', 'ROW', 'EXCEL', 'N', 'P', 'P', 'FULL', 'ECPR-XXXX'
    FROM dual WHERE NOT EXISTS (SELECT 1 FROM OV_IMP_SOURCE_INTERFACE WHERE CODE='CLAUDE_WELL_TEST');

  -- 2) SOURCE MAPPINGS -----------------------------------------------------------------------------
  -- WELL (key)
  UPDATE OV_IMP_SOURCE_MAPPING SET NAME='Well', SORT_ORDER='10', PATH_ORIGIN='Data.A1', TYPE='KEY_LIST',
         VALUE_TYPE='STRING', REV_TEXT='ECPR-XXXX'
   WHERE MAPPING_CODE='WELL' AND IMP_SOURCE_INTERFACE_CODE='CLAUDE_WELL_TEST';
  INSERT INTO OV_IMP_SOURCE_MAPPING (OBJECT_START_DATE, SORT_ORDER, MAPPING_CODE, NAME, PATH_ORIGIN, TYPE,
         VALUE_TYPE, IMP_SOURCE_INTERFACE_CODE, REV_TEXT)
  SELECT to_date('1900-01-01T00:00:00','yyyy-mm-dd"T"hh24:mi:ss'), '10', 'WELL', 'Well', 'Data.A1', 'KEY_LIST',
         'STRING', 'CLAUDE_WELL_TEST', 'ECPR-XXXX'
    FROM dual WHERE NOT EXISTS (SELECT 1 FROM OV_IMP_SOURCE_MAPPING WHERE MAPPING_CODE='WELL' AND IMP_SOURCE_INTERFACE_CODE='CLAUDE_WELL_TEST');

  -- DATE (key)
  UPDATE OV_IMP_SOURCE_MAPPING SET NAME='Date', SORT_ORDER='20', PATH_ORIGIN='Data.A1', TYPE='KEY_LIST',
         VALUE_TYPE='DATE', REV_TEXT='ECPR-XXXX'
   WHERE MAPPING_CODE='DATE' AND IMP_SOURCE_INTERFACE_CODE='CLAUDE_WELL_TEST';
  INSERT INTO OV_IMP_SOURCE_MAPPING (OBJECT_START_DATE, SORT_ORDER, MAPPING_CODE, NAME, PATH_ORIGIN, TYPE,
         VALUE_TYPE, IMP_SOURCE_INTERFACE_CODE, REV_TEXT)
  SELECT to_date('1900-01-01T00:00:00','yyyy-mm-dd"T"hh24:mi:ss'), '20', 'DATE', 'Date', 'Data.A1', 'KEY_LIST',
         'DATE', 'CLAUDE_WELL_TEST', 'ECPR-XXXX'
    FROM dual WHERE NOT EXISTS (SELECT 1 FROM OV_IMP_SOURCE_MAPPING WHERE MAPPING_CODE='DATE' AND IMP_SOURCE_INTERFACE_CODE='CLAUDE_WELL_TEST');

  -- PRESSURE (data value -> AVG_BH_PRESS)
  UPDATE OV_IMP_SOURCE_MAPPING SET NAME='Pressure', SORT_ORDER='30', PATH_ORIGIN='Data.A1', TYPE='DATA',
         VALUE_TYPE='NUMBER', EC_KEY='claudePress', KEY_1='ROWS:WELL', KEY_2='ROWS:DATE', REV_TEXT='ECPR-XXXX'
   WHERE MAPPING_CODE='PRESSURE' AND IMP_SOURCE_INTERFACE_CODE='CLAUDE_WELL_TEST';
  INSERT INTO OV_IMP_SOURCE_MAPPING (OBJECT_START_DATE, SORT_ORDER, MAPPING_CODE, NAME, PATH_ORIGIN, TYPE,
         VALUE_TYPE, EC_KEY, KEY_1, KEY_2, IMP_SOURCE_INTERFACE_CODE, REV_TEXT)
  SELECT to_date('1900-01-01T00:00:00','yyyy-mm-dd"T"hh24:mi:ss'), '30', 'PRESSURE', 'Pressure', 'Data.A1',
         'DATA', 'NUMBER', 'claudePress', 'ROWS:WELL', 'ROWS:DATE', 'CLAUDE_WELL_TEST', 'ECPR-XXXX'
    FROM dual WHERE NOT EXISTS (SELECT 1 FROM OV_IMP_SOURCE_MAPPING WHERE MAPPING_CODE='PRESSURE' AND IMP_SOURCE_INTERFACE_CODE='CLAUDE_WELL_TEST');

  -- 3) SOURCE MAPPING COMMANDS (paths) -- parent mapping resolved by subquery on its business code ----
  -- WELL: Move(0,1) .. FindVertical("")
  UPDATE OV_IMP_SOURCE_PATH SET SOURCE_PATH='Move', PATH_PARAM_1='0', PATH_PARAM_2='1', REV_TEXT='ECPR-XXXX'
   WHERE IMP_SOURCE_INTERFACE_CODE='CLAUDE_WELL_TEST' AND IMP_SOURCE_MAPPING_CODE='WELL' AND SOURCE_TYPE='UPPER_LEFT';
  INSERT INTO OV_IMP_SOURCE_PATH (OBJECT_START_DATE, SORT_ORDER, SOURCE_TYPE, SOURCE_PATH, PATH_PARAM_1, PATH_PARAM_2, IMP_SOURCE_MAPPING_ID, REV_TEXT)
  SELECT to_date('1900-01-01T00:00:00','yyyy-mm-dd"T"hh24:mi:ss'), 10, 'UPPER_LEFT', 'Move', '0', '1',
         (SELECT OBJECT_ID FROM OV_IMP_SOURCE_MAPPING WHERE MAPPING_CODE='WELL' AND IMP_SOURCE_INTERFACE_CODE='CLAUDE_WELL_TEST'), 'ECPR-XXXX'
    FROM dual WHERE NOT EXISTS (SELECT 1 FROM OV_IMP_SOURCE_PATH WHERE IMP_SOURCE_INTERFACE_CODE='CLAUDE_WELL_TEST' AND IMP_SOURCE_MAPPING_CODE='WELL' AND SOURCE_TYPE='UPPER_LEFT');
  UPDATE OV_IMP_SOURCE_PATH SET SOURCE_PATH='FindVertical', PATH_PARAM_1='""', PATH_PARAM_2=null, REV_TEXT='ECPR-XXXX'
   WHERE IMP_SOURCE_INTERFACE_CODE='CLAUDE_WELL_TEST' AND IMP_SOURCE_MAPPING_CODE='WELL' AND SOURCE_TYPE='LOWER_RIGHT';
  INSERT INTO OV_IMP_SOURCE_PATH (OBJECT_START_DATE, SORT_ORDER, SOURCE_TYPE, SOURCE_PATH, PATH_PARAM_1, IMP_SOURCE_MAPPING_ID, REV_TEXT)
  SELECT to_date('1900-01-01T00:00:00','yyyy-mm-dd"T"hh24:mi:ss'), 20, 'LOWER_RIGHT', 'FindVertical', '""',
         (SELECT OBJECT_ID FROM OV_IMP_SOURCE_MAPPING WHERE MAPPING_CODE='WELL' AND IMP_SOURCE_INTERFACE_CODE='CLAUDE_WELL_TEST'), 'ECPR-XXXX'
    FROM dual WHERE NOT EXISTS (SELECT 1 FROM OV_IMP_SOURCE_PATH WHERE IMP_SOURCE_INTERFACE_CODE='CLAUDE_WELL_TEST' AND IMP_SOURCE_MAPPING_CODE='WELL' AND SOURCE_TYPE='LOWER_RIGHT');

  -- DATE: Move(1,1) .. FindVertical("")
  UPDATE OV_IMP_SOURCE_PATH SET SOURCE_PATH='Move', PATH_PARAM_1='1', PATH_PARAM_2='1', REV_TEXT='ECPR-XXXX'
   WHERE IMP_SOURCE_INTERFACE_CODE='CLAUDE_WELL_TEST' AND IMP_SOURCE_MAPPING_CODE='DATE' AND SOURCE_TYPE='UPPER_LEFT';
  INSERT INTO OV_IMP_SOURCE_PATH (OBJECT_START_DATE, SORT_ORDER, SOURCE_TYPE, SOURCE_PATH, PATH_PARAM_1, PATH_PARAM_2, IMP_SOURCE_MAPPING_ID, REV_TEXT)
  SELECT to_date('1900-01-01T00:00:00','yyyy-mm-dd"T"hh24:mi:ss'), 10, 'UPPER_LEFT', 'Move', '1', '1',
         (SELECT OBJECT_ID FROM OV_IMP_SOURCE_MAPPING WHERE MAPPING_CODE='DATE' AND IMP_SOURCE_INTERFACE_CODE='CLAUDE_WELL_TEST'), 'ECPR-XXXX'
    FROM dual WHERE NOT EXISTS (SELECT 1 FROM OV_IMP_SOURCE_PATH WHERE IMP_SOURCE_INTERFACE_CODE='CLAUDE_WELL_TEST' AND IMP_SOURCE_MAPPING_CODE='DATE' AND SOURCE_TYPE='UPPER_LEFT');
  UPDATE OV_IMP_SOURCE_PATH SET SOURCE_PATH='FindVertical', PATH_PARAM_1='""', PATH_PARAM_2=null, REV_TEXT='ECPR-XXXX'
   WHERE IMP_SOURCE_INTERFACE_CODE='CLAUDE_WELL_TEST' AND IMP_SOURCE_MAPPING_CODE='DATE' AND SOURCE_TYPE='LOWER_RIGHT';
  INSERT INTO OV_IMP_SOURCE_PATH (OBJECT_START_DATE, SORT_ORDER, SOURCE_TYPE, SOURCE_PATH, PATH_PARAM_1, IMP_SOURCE_MAPPING_ID, REV_TEXT)
  SELECT to_date('1900-01-01T00:00:00','yyyy-mm-dd"T"hh24:mi:ss'), 20, 'LOWER_RIGHT', 'FindVertical', '""',
         (SELECT OBJECT_ID FROM OV_IMP_SOURCE_MAPPING WHERE MAPPING_CODE='DATE' AND IMP_SOURCE_INTERFACE_CODE='CLAUDE_WELL_TEST'), 'ECPR-XXXX'
    FROM dual WHERE NOT EXISTS (SELECT 1 FROM OV_IMP_SOURCE_PATH WHERE IMP_SOURCE_INTERFACE_CODE='CLAUDE_WELL_TEST' AND IMP_SOURCE_MAPPING_CODE='DATE' AND SOURCE_TYPE='LOWER_RIGHT');

  -- PRESSURE: Move(2,1) .. FindVertical("")
  UPDATE OV_IMP_SOURCE_PATH SET SOURCE_PATH='Move', PATH_PARAM_1='2', PATH_PARAM_2='1', REV_TEXT='ECPR-XXXX'
   WHERE IMP_SOURCE_INTERFACE_CODE='CLAUDE_WELL_TEST' AND IMP_SOURCE_MAPPING_CODE='PRESSURE' AND SOURCE_TYPE='UPPER_LEFT';
  INSERT INTO OV_IMP_SOURCE_PATH (OBJECT_START_DATE, SORT_ORDER, SOURCE_TYPE, SOURCE_PATH, PATH_PARAM_1, PATH_PARAM_2, IMP_SOURCE_MAPPING_ID, REV_TEXT)
  SELECT to_date('1900-01-01T00:00:00','yyyy-mm-dd"T"hh24:mi:ss'), 10, 'UPPER_LEFT', 'Move', '2', '1',
         (SELECT OBJECT_ID FROM OV_IMP_SOURCE_MAPPING WHERE MAPPING_CODE='PRESSURE' AND IMP_SOURCE_INTERFACE_CODE='CLAUDE_WELL_TEST'), 'ECPR-XXXX'
    FROM dual WHERE NOT EXISTS (SELECT 1 FROM OV_IMP_SOURCE_PATH WHERE IMP_SOURCE_INTERFACE_CODE='CLAUDE_WELL_TEST' AND IMP_SOURCE_MAPPING_CODE='PRESSURE' AND SOURCE_TYPE='UPPER_LEFT');
  UPDATE OV_IMP_SOURCE_PATH SET SOURCE_PATH='FindVertical', PATH_PARAM_1='""', PATH_PARAM_2=null, REV_TEXT='ECPR-XXXX'
   WHERE IMP_SOURCE_INTERFACE_CODE='CLAUDE_WELL_TEST' AND IMP_SOURCE_MAPPING_CODE='PRESSURE' AND SOURCE_TYPE='LOWER_RIGHT';
  INSERT INTO OV_IMP_SOURCE_PATH (OBJECT_START_DATE, SORT_ORDER, SOURCE_TYPE, SOURCE_PATH, PATH_PARAM_1, IMP_SOURCE_MAPPING_ID, REV_TEXT)
  SELECT to_date('1900-01-01T00:00:00','yyyy-mm-dd"T"hh24:mi:ss'), 20, 'LOWER_RIGHT', 'FindVertical', '""',
         (SELECT OBJECT_ID FROM OV_IMP_SOURCE_MAPPING WHERE MAPPING_CODE='PRESSURE' AND IMP_SOURCE_INTERFACE_CODE='CLAUDE_WELL_TEST'), 'ECPR-XXXX'
    FROM dual WHERE NOT EXISTS (SELECT 1 FROM OV_IMP_SOURCE_PATH WHERE IMP_SOURCE_INTERFACE_CODE='CLAUDE_WELL_TEST' AND IMP_SOURCE_MAPPING_CODE='PRESSURE' AND SOURCE_TYPE='LOWER_RIGHT');

  -- 4) TARGET MAPPING : claudePress -> PWEL_DAY_STATUS.AVG_BH_PRESS (Class Key 1=KEY_1, Key 2=KEY_2) -----
  UPDATE OV_IMP_TARGET_MAPPING SET CLASS='PWEL_DAY_STATUS', ATTRIBUTE='AVG_BH_PRESS', CLASS_KEY_1='KEY_1',
         CLASS_KEY_2='KEY_2', REV_TEXT='ECPR-XXXX'
   WHERE EC_KEY='claudePress' AND IMP_SOURCE_INTERFACE_CODE='CLAUDE_WELL_TEST';
  INSERT INTO OV_IMP_TARGET_MAPPING (CLASS, OBJECT_START_DATE, ATTRIBUTE, EC_KEY, CLASS_KEY_1, CLASS_KEY_2,
         IMP_SOURCE_INTERFACE_CODE, REV_TEXT)
  SELECT 'PWEL_DAY_STATUS', to_date('1900-01-01T00:00:00','yyyy-mm-dd"T"hh24:mi:ss'), 'AVG_BH_PRESS',
         'claudePress', 'KEY_1', 'KEY_2', 'CLAUDE_WELL_TEST', 'ECPR-XXXX'
    FROM dual WHERE NOT EXISTS (SELECT 1 FROM OV_IMP_TARGET_MAPPING WHERE EC_KEY='claudePress' AND IMP_SOURCE_INTERFACE_CODE='CLAUDE_WELL_TEST');

end;
/
