"""Convert a JasperReports 7 COMPACT JRXML into JasperReports 6.x CLASSIC JRXML.

Why this is a syntax transformation and not a feature downgrade: an XML inventory of the INPEX
reports (see inventory.py) shows they use only five element kinds - staticText, rectangle, line,
textField, image - plus styles/conditionalStyles, parameters, query, fields, variables and the
standard bands. Every one of those exists in JasperReports 6.x. Nothing JR7-only is used, so a
1:1 mapping exists and no content need be lost.

Three things that bite and are handled explicitly:

  1. BAND WRAPPING. JR7 puts elements directly inside <title height=..>; 6.x requires
     <title><band height=..>..</band></title>. <detail> already carries its own <band>.
  2. XSD CHILD ORDER. 6.x validates order strictly, and it is NOT the order JR7 files use -
     <summary> must come AFTER <pageFooter>, not before. Emitting source order fails validation.
  3. BOOLEAN ATTRIBUTE PREFIX. JR7 dropped the "is" prefix: bold/italic/forPrompting/
     blankWhenNull/removeLineWhenBlank -> isBold/isItalic/isForPrompting/isBlankWhenNull/
     isRemoveLineWhenBlank.

    py jr7_to_jr6.py <in.jrxml> <out.jrxml>
"""
import sys
import xml.etree.ElementTree as ET

HEADER = (
    '<?xml version="1.0" encoding="UTF-8"?>\n'
    '<!-- GENERATED by _jr6-downgrade/jr7_to_jr6.py from the JasperReports 7 compact source.\n'
    '     Do not hand-edit: edit the 7.x JRXML and re-run the converter. -->\n'
    '<jasperReport xmlns="http://jasperreports.sourceforge.net/jasperreports"\n'
    '              xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"\n'
    '              xsi:schemaLocation="http://jasperreports.sourceforge.net/jasperreports'
    ' http://jasperreports.sourceforge.net/xsd/jasperreport.xsd"\n'
)

# JR7 name -> 6.x name, for boolean attributes that lost their "is" prefix in 7.x
BOOL_RENAME = {
    "bold": "isBold",
    "italic": "isItalic",
    "underline": "isUnderline",
    "strikeThrough": "isStrikeThrough",
    "pdfEmbedded": "isPdfEmbedded",
    "default": "isDefault",
    "forPrompting": "isForPrompting",
    "blankWhenNull": "isBlankWhenNull",
    "removeLineWhenBlank": "isRemoveLineWhenBlank",
    "printRepeatedValues": "isPrintRepeatedValues",
    "printInFirstWholeBand": "isPrintInFirstWholeBand",
    "printWhenDetailOverflows": "isPrintWhenDetailOverflows",
    "stretchWithOverflow": "isStretchWithOverflow",
    "usingCache": "isUsingCache",
    "lazy": "isLazy",
    "titleNewPage": "isTitleNewPage",
    "summaryNewPage": "isSummaryNewPage",
    "summaryWithPageHeaderAndFooter": "isSummaryWithPageHeaderAndFooter",
    "floatColumnFooter": "isFloatColumnFooter",
    "ignorePagination": "isIgnorePagination",
}

# Every attribute this converter knows how to place, per element kind. Anything on a source
# element that is NOT listed here is a SILENT DROP - the report would still compile and fill,
# and the defect would only show up as missing ink in the PDF. That is exactly how the dropped
# <box> on <style> cost every cell border while all gates passed, so unknown attributes are a
# hard error instead.
COMMON_ATTRS = {"kind", "x", "y", "width", "height", "style", "mode", "forecolor",
                "backcolor", "removeLineWhenBlank", "printWhenExpression",
                "hTextAlign", "vTextAlign", "fontName", "fontSize", "bold", "italic",
                "underline", "printRepeatedValues", "printInFirstWholeBand",
                "printWhenDetailOverflows",
                # markup="styled"/"html" lives on <textElement> in 6.x; it is how R07.003's
                # bold "Disclaimer:" inside otherwise-plain text is produced, so losing it
                # would quietly change rendered text weight
                "markup", "rotation", "lineSpacing"}
KIND_ATTRS = {
    "staticText": COMMON_ATTRS,
    "textField": COMMON_ATTRS | {"pattern", "blankWhenNull", "evaluationTime",
                                 "stretchWithOverflow", "evaluationGroup"},
    "rectangle": COMMON_ATTRS | {"radius"},
    "line": COMMON_ATTRS | {"direction"},
    "ellipse": COMMON_ATTRS,
    "image": COMMON_ATTRS | {"scaleImage", "onErrorType", "usingCache", "lazy",
                             "hImageAlign", "vImageAlign", "evaluationTime"},
}


# Child tags this converter knows how to place, per kind. The attribute allowlist above was
# NOT enough on its own: R07.001's generator emits <printWhenExpression> as a CHILD element
# while R07.012 uses an attribute, and the attribute-only guard let all 4,336 of R07.001's
# child-form conditions be dropped silently - every detail page then rendered all 6 records.
# A guard that covers only half the shapes a construct can take is not a guard.
KIND_CHILDREN = {
    "staticText": {"text", "box", "printWhenExpression"},
    "textField": {"expression", "box", "printWhenExpression"},
    "rectangle": {"pen", "box", "printWhenExpression"},
    "line": {"pen", "box", "printWhenExpression"},
    "ellipse": {"pen", "box", "printWhenExpression"},
    "image": {"expression", "box", "printWhenExpression"},
}


def check_attrs(el):
    kind = el.get("kind")
    known = KIND_ATTRS.get(kind)
    if known is None:
        raise SystemExit(f"unhandled element kind={kind!r} - converter needs extending")
    unknown = set(el.attrib) - known
    if unknown:
        raise SystemExit(
            f"REFUSING to convert: element kind={kind!r} has attribute(s) this converter "
            f"does not place: {sorted(unknown)}\n"
            f"  Add them to KIND_ATTRS and to the emitter, or they would be silently lost.")
    unknown_kids = {c.tag for c in el} - KIND_CHILDREN[kind]
    if unknown_kids:
        raise SystemExit(
            f"REFUSING to convert: element kind={kind!r} has child element(s) this converter "
            f"does not place: {sorted(unknown_kids)}\n"
            f"  Add them to KIND_CHILDREN and to the emitter, or they would be silently lost.")


def print_when(el):
    """printWhenExpression appears in BOTH shapes in this project's JR7 files: as an attribute
    (hand-built reports) and as a child element (generated reports). Accept either."""
    a = el.get("printWhenExpression")
    if a is not None:
        return a
    c = el.find("printWhenExpression")
    return None if c is None else (c.text or "")

# 6.x jasperReport child order, per the XSD. Anything not listed is emitted in source order
# before the bands.
BAND_ORDER = ["background", "title", "pageHeader", "columnHeader", "detail",
              "columnFooter", "pageFooter", "lastPageFooter", "summary", "noData"]

# bands that in JR7 hold elements directly and in 6.x need an inner <band>
NEEDS_BAND_WRAP = {"background", "title", "pageHeader", "columnHeader",
                   "columnFooter", "pageFooter", "lastPageFooter", "summary", "noData"}

# element attributes that belong on <reportElement> rather than the element tag
REPORT_ELEMENT_ATTRS = ["style", "x", "y", "width", "height", "mode", "forecolor",
                        "backcolor", "removeLineWhenBlank", "printRepeatedValues",
                        "printInFirstWholeBand", "printWhenDetailOverflows"]


def esc_attr(v):
    return (v.replace("&", "&amp;").replace("<", "&lt;")
             .replace(">", "&gt;").replace('"', "&quot;"))


def cdata(text):
    """CDATA cannot contain its own terminator; nothing else needs escaping inside it."""
    return "<![CDATA[" + (text or "").replace("]]>", "]]&gt;") + "]]>"


def attrs(pairs):
    return "".join(f' {k}="{esc_attr(str(v))}"' for k, v in pairs if v is not None)


def rename_bools(d):
    return {BOOL_RENAME.get(k, k): v for k, v in d.items()}


def emit_pen(el, indent):
    """<pen>/<topPen>/... pass through unchanged - identical in both versions."""
    return f'{indent}<{el.tag}{attrs(el.attrib.items())}/>\n'


# 6.x XSD order for <box> children. JR7 files list them in whatever order the author wrote,
# and 6.x rejects anything else - R07.004 failed with "found leftPen, expected rightPen"
# purely because the source had bottomPen before leftPen.
BOX_PEN_ORDER = ["pen", "topPen", "leftPen", "bottomPen", "rightPen"]


def emit_box(box, indent):
    if box is None:
        return ""
    kids = list(box)
    if not kids:
        return f'{indent}<box{attrs(box.attrib.items())}/>\n'
    unknown = {k.tag for k in kids} - set(BOX_PEN_ORDER)
    if unknown:
        raise SystemExit(f"REFUSING to convert: <box> has unexpected child(ren) "
                         f"{sorted(unknown)} - would be silently dropped or misordered")
    out = f'{indent}<box{attrs(box.attrib.items())}>\n'
    for tag in BOX_PEN_ORDER:
        for k in kids:
            if k.tag == tag:
                out += emit_pen(k, indent + "    ")
    out += f'{indent}</box>\n'
    return out


def emit_report_element(el, indent):
    """Build <reportElement>, moving positional/style attributes off the element tag."""
    pairs = [(k, el.get(k)) for k in REPORT_ELEMENT_ATTRS if el.get(k) is not None]
    pairs = list(rename_bools(dict(pairs)).items())
    pwe = print_when(el)
    if pwe is None:
        return f'{indent}<reportElement{attrs(pairs)}/>\n'
    out = f'{indent}<reportElement{attrs(pairs)}>\n'
    out += f'{indent}    <printWhenExpression>{cdata(pwe)}</printWhenExpression>\n'
    out += f'{indent}</reportElement>\n'
    return out


def emit_text_element(el, indent):
    """<textElement> carries alignment; <font> carries any inline font overrides."""
    pairs = []
    if el.get("hTextAlign"):
        pairs.append(("textAlignment", el.get("hTextAlign")))
    if el.get("vTextAlign"):
        pairs.append(("verticalAlignment", el.get("vTextAlign")))
    for a in ("markup", "rotation", "lineSpacing"):
        if el.get(a):
            pairs.append((a, el.get(a)))
    font = [("fontName", el.get("fontName")), ("size", el.get("fontSize")),
            ("isBold", el.get("bold")), ("isItalic", el.get("italic")),
            ("isUnderline", el.get("underline"))]
    font = [(k, v) for k, v in font if v is not None]
    if not pairs and not font:
        return ""
    if not font:
        return f'{indent}<textElement{attrs(pairs)}/>\n'
    out = f'{indent}<textElement{attrs(pairs)}>\n'
    out += f'{indent}    <font{attrs(font)}/>\n'
    out += f'{indent}</textElement>\n'
    return out


def child_text(el, tag):
    c = el.find(tag)
    return None if c is None else (c.text or "")


def emit_element(el, indent):
    check_attrs(el)
    kind = el.get("kind")
    box = el.find("box")
    re_xml = emit_report_element(el, indent + "    ")

    if kind == "staticText":
        out = f'{indent}<staticText>\n' + re_xml
        out += emit_box(box, indent + "    ")
        out += emit_text_element(el, indent + "    ")
        out += f'{indent}    <text>{cdata(child_text(el, "text"))}</text>\n'
        return out + f'{indent}</staticText>\n'

    if kind == "textField":
        # pattern / isBlankWhenNull / evaluationTime live on the <textField> tag in 6.x
        tf = [("pattern", el.get("pattern")),
              ("isBlankWhenNull", el.get("blankWhenNull")),
              ("isStretchWithOverflow", el.get("stretchWithOverflow")),
              ("evaluationTime", el.get("evaluationTime")),
              ("evaluationGroup", el.get("evaluationGroup"))]
        out = f'{indent}<textField{attrs([(k, v) for k, v in tf if v is not None])}>\n'
        out += re_xml
        out += emit_box(box, indent + "    ")
        out += emit_text_element(el, indent + "    ")
        out += (f'{indent}    <textFieldExpression>'
                f'{cdata(child_text(el, "expression"))}</textFieldExpression>\n')
        return out + f'{indent}</textField>\n'

    if kind in ("rectangle", "line", "ellipse"):
        shape = [("radius", el.get("radius")), ("direction", el.get("direction"))]
        out = (f'{indent}<{kind}'
               f'{attrs([(k, v) for k, v in shape if v is not None])}>\n') + re_xml
        pen = el.find("pen")
        if pen is not None:
            out += f'{indent}    <graphicElement>\n'
            out += emit_pen(pen, indent + "        ")
            out += f'{indent}    </graphicElement>\n'
        return out + f'{indent}</{kind}>\n'

    if kind == "image":
        img = [("scaleImage", el.get("scaleImage")),
               ("hImageAlign", el.get("hImageAlign")),
               ("vImageAlign", el.get("vImageAlign")),
               ("isUsingCache", el.get("usingCache")),
               ("isLazy", el.get("lazy")),
               ("evaluationTime", el.get("evaluationTime")),
               ("onErrorType", el.get("onErrorType"))]
        out = f'{indent}<image{attrs([(k, v) for k, v in img if v is not None])}>\n'
        out += re_xml
        out += emit_box(box, indent + "    ")
        out += (f'{indent}    <imageExpression>'
                f'{cdata(child_text(el, "expression"))}</imageExpression>\n')
        return out + f'{indent}</image>\n'

    raise SystemExit(f"unhandled element kind={kind!r} - converter needs extending")


def emit_style(st, indent):
    pairs = list(rename_bools(dict(st.attrib)).items())
    conds = st.findall("conditionalStyle")
    # A <style> can also carry its own <box> with pens - and in these reports that is where
    # the ENTIRE cell grid comes from. An earlier version of this function only looked at
    # conditionalStyle children and silently dropped 11 of the 14 <box> elements, which cost
    # every border in the rendered PDF (165 drawings instead of 1438).
    box = st.find("box")
    if not conds and box is None:
        return f'{indent}<style{attrs(pairs)}/>\n'
    out = f'{indent}<style{attrs(pairs)}>\n'
    # 6.x XSD order inside <style>: box before conditionalStyle
    out += emit_box(box, indent + "    ")
    for c in conds:
        # JR7 collapses this to attributes; 6.x needs the nested form
        cond = c.get("conditionExpression")
        rest = [(k, v) for k, v in rename_bools(dict(c.attrib)).items()
                if k != "conditionExpression"]
        out += f'{indent}    <conditionalStyle>\n'
        out += (f'{indent}        <conditionExpression>{cdata(cond)}'
                f'</conditionExpression>\n')
        out += f'{indent}        <style{attrs(rest)}/>\n'
        out += f'{indent}    </conditionalStyle>\n'
    return out + f'{indent}</style>\n'


def emit_band_body(container, indent):
    out = ""
    for el in container.findall("element"):
        out += emit_element(el, indent)
    return out


def main():
    src, dst = sys.argv[1], sys.argv[2]
    root = ET.parse(src).getroot()

    # ---- root ------------------------------------------------------------------
    order = ["name", "language", "pageWidth", "pageHeight", "orientation", "columnWidth",
             "leftMargin", "rightMargin", "topMargin", "bottomMargin", "whenNoDataType",
             "titleNewPage", "summaryNewPage", "isFloatColumnFooter", "ignorePagination"]
    ra = rename_bools(dict(root.attrib))
    pairs = [(k, ra.pop(k)) for k in order if k in ra] + sorted(ra.items())
    out = HEADER + "             " + attrs(pairs) + ">\n\n"

    # ---- styles, parameters, query, fields, variables (XSD order) --------------
    for st in root.findall("style"):
        out += emit_style(st, "    ")
    out += "\n"

    for p in root.findall("parameter"):
        pa = list(rename_bools(dict(p.attrib)).items())
        dv = p.find("defaultValueExpression")
        if dv is None:
            out += f'    <parameter{attrs(pa)}/>\n'
        else:
            out += f'    <parameter{attrs(pa)}>\n'
            out += (f'        <defaultValueExpression>{cdata(dv.text)}'
                    f'</defaultValueExpression>\n')
            out += '    </parameter>\n'
    out += "\n"

    q = root.find("query")
    if q is not None:
        # <query language="sql"> becomes <queryString> - the tag itself is renamed in 6.x
        out += f'    <queryString>\n        {cdata(q.text)}\n    </queryString>\n\n'

    for f in root.findall("field"):
        out += f'    <field{attrs(f.attrib.items())}/>\n'
    out += "\n"

    for v in root.findall("variable"):
        out += f'    <variable{attrs(v.attrib.items())}>\n'
        out += (f'        <variableExpression>{cdata(child_text(v, "expression"))}'
                f'</variableExpression>\n')
        out += '    </variable>\n'
    out += "\n"

    # ---- bands, reordered to the 6.x XSD sequence ------------------------------
    emitted = 0
    for tag in BAND_ORDER:
        b = root.find(tag)
        if b is None:
            continue
        emitted += 1
        if tag in NEEDS_BAND_WRAP:
            ba = [(k, v) for k, v in b.attrib.items()]
            out += f'    <{tag}>\n        <band{attrs(ba)}>\n'
            out += emit_band_body(b, "            ")
            out += f'        </band>\n    </{tag}>\n\n'
        else:
            out += f'    <{tag}>\n'
            for band in b.findall("band"):
                out += f'        <band{attrs(band.attrib.items())}>\n'
                out += emit_band_body(band, "            ")
                out += '        </band>\n'
            out += f'    </{tag}>\n\n'

    out += "</jasperReport>\n"

    with open(dst, "w", encoding="utf-8") as fh:
        fh.write(out)

    print(f"converted: {src}")
    print(f"      -> : {dst}")
    print(f"  bands emitted: {emitted}   "
          f"elements: {len(root.findall('.//element'))}")


if __name__ == "__main__":
    main()
