#!/usr/bin/env python3
"""
Regenerate STATUS.md from git log + static context.
Run at end of session before final commit.

Usage: python scripts/update_status.py
"""
import subprocess
from datetime import date

REPO_ROOT = subprocess.check_output(
    ["git", "rev-parse", "--show-toplevel"], text=True
).strip()


def git(*args):
    return subprocess.check_output(["git", "-C", REPO_ROOT] + list(args), text=True).strip()


def recent_commits(n=10):
    log = git("log", f"-{n}", "--pretty=format:%h|%ad|%s", "--date=short")
    rows = []
    for line in log.splitlines():
        sha, d, msg = line.split("|", 2)
        rows.append((sha, d, msg))
    return rows


def unpushed_count():
    try:
        branch = git("branch", "--show-current")
        out = git("rev-list", f"origin/{branch}..HEAD", "--count")
        return int(out)
    except Exception:
        return 0


def build_status():
    today = date.today().isoformat()
    commits = recent_commits(10)

    commit_table = "\n".join(
        f"| `{sha}` | {d} | {msg[:80]}{'…' if len(msg)>80 else ''} |"
        for sha, d, msg in commits
    )

    unpushed = unpushed_count()
    push_status = f"✅ Up to date" if unpushed == 0 else f"⚠️ {unpushed} unpushed commit(s)"

    content = f"""# STATUS — {today}
_Auto-generated by scripts/update_status.py. Jira section requires manual update._

## ATTENTION
- **ECPR-31034** — Email notifications must be re-based from `PCI_Release`, not `develop`. Grant flagged this.
- **2 UAT blockers** — Tahura + Dinesh tagged. Follow up Monday.
- **PRs #603–606** — All approved, check merge status.
- **1.0.37-RC1 on ECaaS TEST** — Verify your changes.

## Active Jira Tickets
| Ticket | Summary | Status | Assignee |
|--------|---------|--------|----------|
| ECPR-31034 | Issue_1044F: Email — Scarborough Upstream Monthly Production Allocation | Solution Released | Jamilin Azizan |
| ECPR-31035 | Issue_1044G: Email — Burrup LNG Park LNG Train 1 Manager Report | Solution Released | Jamilin Azizan |
| ECPR-31036 | WS H: Upgrade log4j to v2.X | In Progress | Grant Hewton |
| ECPR-31049 | Issue_1057: Update manual input composition (ZWP_CH4 Methane Analyser) | Solution Released | Choong Yin Lee |
| ECPR-31032 | Issue_1044D: Email — Burrup LNG Park Monthly Allocation (Scarborough) | In Progress | Choong Yin Lee |
| ECPR-31028 | Issue_1044A: Email — Scarborough Upstream Daily Partner Report | In Progress | Choong Yin Lee |
| ECPR-31016 | Issue_1047: Deferment error — duplicate daily deferment event | In Progress | Choong Yin Lee |
| ECPR-31068 | Issue_1061/1063: Well Analysis & PHD tags | In Progress | Dinesh Agarwala |
| ECPR-31058 | Issue_1060: Add SCA and T2 PHD Tags | In Progress | Grant Hewton |

_Last Jira sync: 2026-06-13. Run a Jira search in session to refresh._

## Automation Repo — Git Status
**Push status:** {push_status}

### Recent Commits
| SHA | Date | Message |
|-----|------|---------|
{commit_table}

## Queue (approved, awaiting arm)
- daily-status-reconcile (daily 08:00 AWST)
- woodside-project-digest (Monday 08:30 AWST)
- morning-briefing (daily 08:00 AWST)

## Context Notes
- **Dev env URL**: https://dev.non-prod.plp.wde.ecaas.cloud/ (needs AWS ECaaS non-prod VPN)
- **Automation scorecard**: see `docs/automation-scorecard.md`
- **N-series progress**: N1 (4 object types + sub-daily) ✅ | N3 P→V ✅ | N3 V→A build-ready

---
_Run `python scripts/update_status.py` to regenerate. For Jira refresh, ask Claude to query Jira in-session._
"""
    return content


if __name__ == "__main__":
    status_path = f"{REPO_ROOT}/STATUS.md"
    content = build_status()
    # encoding="utf-8" is required: commit messages / status content contain non-cp1252 chars
    # (✅ → — etc.); the default Windows codec (cp1252) raises UnicodeEncodeError without this.
    with open(status_path, "w", encoding="utf-8") as f:
        f.write(content)
    print(f"STATUS.md updated -> {status_path}")
