"""verify_screen.py - RUN the IUD verification gates and emit ticks from REAL results.

The point: a checklist tick must be a PRODUCT of an executed command, never a hand-typed claim.
This script RUNS each runnable gate, captures the real output, and writes a VERIFY-REPORT.md whose
[x]/[ ] come from actual exit codes / pass counts. Exits non-zero if any gate fails -> use as the
pre-PR gate for EC IUD screens (see docs/IUD-DELIVERABLE-CHECKLIST.md, CLAUDE.md 'NO GUESSING' rule).

Usage:
    py scripts/verify_screen.py --name "Report Area" \
        --t3 workstreams/master-plan/ec-automation/pageobjects/Reporting/report_area_page.resource \
        --suite workstreams/master-plan/ec-automation/tests/Reporting/report_area_iud.robot \
        --driver workstreams/master-plan/ec-automation/py/report_area_iud.py \
        --out workstreams/master-plan/ec-automation/screens/Reporting/Report_Area/VERIFY-REPORT.md
    Optional: --no-live (static gates only: robocop + hygiene + dryrun).

Gates run: robocop (10), hygiene (16), dryrun (11), live RF suite (12/13/14/15 via the suite's own
DB asserts + self-clean), Playwright driver (parallel proof). Ticks come from exit codes / parsed counts.
"""
import argparse
import os
import re
import subprocess
import sys
from pathlib import Path

ROOT = Path(os.environ.get("REPO_ROOT") or Path(__file__).resolve().parents[1])
EC = ROOT / "workstreams" / "master-plan" / "ec-automation"
TESTS_RE = re.compile(r"(\d+)\s+tests?,\s+(\d+)\s+passed,\s+(\d+)\s+failed")


def run(cmd, cwd=None, env=None):
    """Run a command, return (exit_code, combined_output)."""
    e = dict(os.environ)
    if env:
        e.update(env)
    p = subprocess.run(cmd, cwd=cwd, env=e, capture_output=True, text=True)
    return p.returncode, (p.stdout or "") + (p.stderr or "")


def robot_counts(output):
    m = None
    for m in TESTS_RE.finditer(output):
        pass
    return (int(m.group(1)), int(m.group(2)), int(m.group(3))) if m else (0, 0, 0)


def main():
    ap = argparse.ArgumentParser()
    ap.add_argument("--name", required=True)
    ap.add_argument("--t3", required=True)
    ap.add_argument("--suite", required=True)
    ap.add_argument("--driver", default="")
    ap.add_argument("--out", default="")
    ap.add_argument("--no-live", action="store_true")
    a = ap.parse_args()

    gates = []  # (id, label, passed, detail)

    # 10 robocop (T3 + suite) - run from repo root; paths are repo-relative
    rc, out = run(["robocop", "check", a.t3, a.suite], cwd=str(ROOT))
    issues = 0 if rc == 0 else len(re.findall(r"\b[A-Z]{3}\d{2}\b", out))
    gates.append(("10", "robocop clean", rc == 0, f"exit={rc}" + ("" if rc == 0 else f", ~{issues} issues")))

    # 16 hygiene
    rc, out = run(["py", str(ROOT / "scripts" / "check_bundle_hygiene.py")], cwd=str(ROOT))
    gates.append(("16", "hygiene (R16 creds / R20 ASCII)", rc == 0, f"exit={rc}"))

    # 11 dryrun
    rc, out = run(["robot", "--dryrun", "--outputdir", str(EC / "results" / "_verify_dry"), a.suite], cwd=str(ROOT))
    t, pw, f = robot_counts(out)
    gates.append(("11", "robot --dryrun", rc == 0 and f == 0 and t > 0, f"{pw}/{t} pass, {f} fail"))

    if not a.no_live:
        # 12/13/14/15 live RF suite (suite carries its own DB asserts + self-clean)
        rc, out = run(["robot", "--outputdir", str(EC / "results" / "_verify_live"), a.suite],
                      cwd=str(ROOT), env={"EC_HEADLESS": "true"})
        t, pw, f = robot_counts(out)
        ok = rc == 0 and f == 0 and t > 0
        gates.append(("12", "LIVE RF suite (DB-verified + self-clean in-suite)", ok, f"{pw}/{t} pass, {f} fail"))

        # Playwright driver (parallel proof)
        if a.driver:
            rc, out = run(["py", "-X", "utf8", a.driver], cwd=str(ROOT), env={"EC_HEADED": "0"})
            ok = rc == 0 and "Overall: ALL PASS" in out
            gates.append(("PW", "Playwright driver 7/7", ok, "Overall: ALL PASS" if ok else f"exit={rc} (see output)"))

    all_ok = all(g[2] for g in gates)
    lines = [f"# VERIFY-REPORT - {a.name}",
             "",
             "_Auto-generated by scripts/verify_screen.py - ticks come from REAL executed gates, not hand-typed._",
             "",
             f"**OVERALL: {'PASS' if all_ok else 'FAIL'}**",
             ""]
    for gid, label, passed, detail in gates:
        lines.append(f"- [{'x' if passed else ' '}] **{gid}** {label} - {detail}")
    if a.no_live:
        lines.append("- [ ] **12** LIVE suite - SKIPPED (--no-live); not verified")
    report = "\n".join(lines) + "\n"

    if a.out:
        Path(a.out).parent.mkdir(parents=True, exist_ok=True)
        Path(a.out).write_text(report, encoding="utf-8")
    print(report)
    print(f"[verify_screen] {a.name}: {'PASS' if all_ok else 'FAIL'}")
    sys.exit(0 if all_ok else 1)


if __name__ == "__main__":
    main()
